config/routes.rb
Rails.application.routes.draw do
  resources :archives
  devise_for :users
  resources :archive
  resources :home
  resources :about
  root 'home#index'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
end

app/models/archive.rb
class Archive < ApplicationRecord
    has_one_attached :troopImage
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: %i[ show edit update destroy ]

  # GET /archives or /archives.json
  def index
    @archives = Archive.all
  end

  # GET /archives/1 or /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
    @archive.troopImage.attach(params[:troopImage])
  end

  # POST /archives or /archives.json
  def create
    @archive = Archive.new(archive_params)

    @archive.writer = current_user.name



    respond_to do |format|
      if @archive.save

        format.html { redirect_to @archive, notice: "Archive was successfully created." }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1 or /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: "Archive was successfully updated." }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1 or /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: "Archive was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def archive_params
      params.require(:archive).permit(:title, :health, :actionrate, :damage, :speed, :defense, :range, :troopDamage, :maxDist, :description, :notes, :writer, :troopImage)
    end
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/_form.html.erb
<%= form_with(model: archive) do |form| %>
  <% if archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
        <% archive.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health %>
  </div>

  <div class="field">
    <%= form.label "Troop Image" %>
    <%= form.file_field :troopImage %>
  </div>

  <div class="field">
    <%= form.label :actionrate %>
    <%= form.text_field :actionrate %>
  </div>

  <div class="field">
    <%= form.label :damage %>
    <%= form.number_field :damage %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed %>
  </div>

  <div class="field">
    <%= form.label :defense %>
    <%= form.number_field :defense %>
  </div>

  <div class="field">
    <%= form.label :range %>
    <%= form.number_field :range %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= archive.writer = current_user.name %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Show', @archive %> |
<%= link_to 'Back', archives_path %>

app/views/archives/index.html.erb
<div class="content">
  <div class="archive-text-column">

    <h1>Archives</h1>
    
    <p>Archive stores all troop information</p>

    <%if current_user %>
      <% if current_user.admin === true %>
        <div id="new-archive-button"><%= link_to 'New Archive', new_archive_path %></div>
      <% end %>
    <% end %>
  </div>

  <div class="posts-container">
        <% @archives.each do |archive| %>
          <div class="archive-row">
            <div class="archive-column">
              <div class="archive-title"><%= link_to archive.title, archive %></div>
              <div class="archive-description"><%= truncate(archive.description, :length => 35) %></div>
              <div class="archive-writer">Created by <%= link_to archive.writer, root_path %></div>              
            </div>
            <div><%= link_to 'Show', archive, class: 'archive-buttons' %></div>
            <% if current_user && current_user.admin %>
              <div><%= link_to 'Edit', edit_archive_path(archive), class: 'archive-buttons' %></div>
              <div><%= link_to 'Destroy', archive, method: :delete, data: { confirm: 'Are you sure?' }, class:'archive-buttons' %></div>
            <% end %>
          </div>
      <% end %>
  </div>
  <br>
</div>

app/views/archives/new.html.erb
<h1>New Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Back', archives_path %>

app/views/archives/show.html.erb
<div class="content">
  <div class="row entire-height">
    <div class="archive-troop-display">
      <div class="align-center">
        <div class="archive-troop-name"><%= @archive.title %></div>
        <% if @archive.troopImage.attached? %>
        <img src="<%=(url_for(@archive.troopImage))%>" alt="Image here", class="archive-image">
        <% end %>
      </div>
    </div>
    <div class="archive-troop-info">
      <div class="archive-troop-info-align-center">
        <h1>Description</h1>
        <div class="archive-divider"></div>
        <p><%= @archive.description %></p>
        <h1>Stats</h1>
        <div class="archive-divider"></div>
        <p>Health: <%= @archive.health %></p>
        <p>Attackrate/actionrate: <%= @archive.actionrate %></p>
        <p>Damage: <%= @archive.damage %></p>
        <p>Speed: <%= @archive.speed %></p>
        <p>Defense: <%= @archive.defense %></p>
        <p>Range: <%= @archive.range %></p>
        <br>
        <h1>Notes</h1>
        <div class="archive-divider"></div>
        <p><%= @archive.notes %></p>
        <br>
        <h1>Comments</h1>
        <div class="archive-divider"></div>
        <p>Bro do you know this is the first ever post? No, it is not.</p>
        <div class="archive-writer">Created by <%= link_to @archive.writer, root_path %>. Created at <%= @archive.created_at %></div>
      </div>
    </div>
  </div>
  
</div>